### PR TITLE
Install PostgreSQL driver

### PR DESCRIPTION
**Pull request by jasonaowen**
Add the [PHP extension for PostgreSQL](https://packages.debian.org/buster/php-pgsql), in preparation for switching database management systems.

But first, make it easier to add packages to our list of installed packages, by consolidating that list into a single install step.

Previously, we were installing apt packages in several passes. Part of the motivation was to make available the tools we needed to configure third party repos, like curl and gpg. Now that we are more securely hardcoding those repos (see #91), rather than fetching configuration over the internet, those tools don't need to be installed in a separate early pass.

There are a few drawbacks to installing in multiple passes. A small one is time: invoking apt multiple times takes longer than invoking it only once, which leads to longer build times.

A bigger problem is it makes it a bit harder for devs to know where and how to add a package to the install list: should it be in one of the existing installation steps? where in the list should it be added? should the existing comment be updated? should it be installed in its own install step? should that have a comment?

Finally, and perhaps most importantly, it makes it difficult to audit the packages we're installing, as that information needs to be drawn from multiple places.

Consolidate all the package installation steps into a single step. Split the packages out to one line per package, and sort them alphabetically.

[PER-8846 Set up MySQL->PostgreSQL switch](https://permanent.atlassian.net/browse/PER-8846)

### CODE REVIEW

**Comment by jasonaowen** [comment]
I *think* this is the only infrastructure change that will be needed to switch databases, but I still have more work to do to be certain. At worst, I'll find there is more I need to do in this repo and we'll need to rebuild images again later, but at best, we can roll this into this week's image build and avoid a later one!

**Comment by jasonaowen** [comment]
cc'ing @slifty because of upcoming work and because that `php7.3` line should probably change to the [`php` dependency package](https://packages.debian.org/buster/php) to ease upgrading. I left that out to avoid (further) scope creep, but mentioning since I noticed it!

**Review by cecilia-donnelly — COMMENTED** [review]
Exciting!  I did not run this but I can see that all the same packages will be installed (plus the new one of course).

I think it would be nice to also install a client for postgres, so devs can ssh into the machines and access the database on the command line as we do currently.  What do you think, @jasonaowen ?

**Comment by jasonaowen** [comment]
You're right, @cecilia-donnelly! And that's also on-path for getting the local environment working, too. I added a commit that configures the [PostgreSQL apt repo](https://wiki.postgresql.org/wiki/Apt) and installs the client.

I rebuilt my local devenv with these changes, and verified that repo was configured correctly and the client was installed.

**Review by cecilia-donnelly — APPROVED** [review]
Thanks, @jasonaowen !  I did not rebuild my local with these changes but I am happy to do so if you'd like.

**Comment by jasonaowen** [comment]
Thanks! I don't think rebuilding your local is necessary. The real test will be rebuilding images tomorrow, but I'm not too worried about that.

**Pull request merged**
