### PR TITLE
Update PHP to 7.4

### PR DESCRIPTION
**Pull request by liam-lloyd**
Our current version of PHP, 7.3, is well past its end of life, so we need to update. 7.4 is past end of life too, but we're starting with an update to 7.4 before proceding to v8.

### CODE REVIEW

**Comment by liam-lloyd** [comment]
Must be deployed at the same time as https://github.com/PermanentOrg/back-end/pull/521

**Review by cecilia-donnelly — APPROVED** [review]
Might be helpful to remind everyone that they'll need to run vagrant up --provision when this goes out. I'm still getting errors on the backend companion, but this looks good!

**Review by cecilia-donnelly — COMMENTED** [review]
I know I've already approved this, but for some reason whenever I reprovision with this branch the site ends up running on PHP 8.2, which is concerning. @meisekimiu , would you be able to try this on your local?

**Review by meisekimiu — APPROVED** [review]
I have PHP 7.4 running properly on my local environment after re-provisioning with this branch.
Screenshot from 2023-12-21 08-28-46

Testing this with [back-end#521](https://github.com/PermanentOrg/back-end/pull/521) seemed to work perfectly. :+1:

**Comment by cecilia-donnelly** [comment]
Thank you so much for double checking, @meisekimiu ! Glad it's just something weird going on for me locally.

**Pull request merged**
