### PR TITLE
Send slack notification once images are done building

### PR DESCRIPTION
**Pull request by xmunoz**

### CODE REVIEW

**Review by cecilia-donnelly — APPROVED** [review]
This looks good!  Out of curiosity / for my knowledge: why separate the notification out into a separate job here instead of adding it as a new step, as you do in the "deploy" workflow?  (My guess is that you want the build to succeed even if the slack notification fails, but always looking to learn more.)

Also not sure how I would test this - could I?

**Comment by xmunoz** [comment]
> why separate the notification out into a separate job here instead of adding it as a new step, as you do in the "deploy" workflow

There are 9 parallel jobs executed by the build workflow, and I figured 9 separate notifications would be annoying. As a separate, un-matrixed job, it will only send one notification.

> (My guess is that you want the build to succeed even if the slack notification fails, but always looking to learn more.)

Yeah, that too. Also, we can add an issue to extend this to add a different notification if the "build" step fails. With this PR, the notification won't be triggered if any of the preceding steps fail.

> Also not sure how I would test this - could I?

Re-trigger the Image build workflow from this branch. It will take a while, and we just did a build, but we've got a couple more hours so why not?

**Comment by cecilia-donnelly** [comment]
Thanks, that's all very helpful!  

Separately, while I'm thinking about it, what has the custom been - do people merge their own PRs or do reviewers merge them?  (I know we're waiting on Andrew's review here anyway.)

**Review by andrewatwood — APPROVED** [review]
Nice, looks good!

**Pull request merged**
